apiVersion: apps/v1
kind: Daemonset
metadata:
  labels:
    app: node-daemonset
  name: node-daemonset
spec:
  selector:
    matchLabels:
      app: node-daemonset
  template:
    metadata: 
      labels:
        app: node-daemonset
    spec:
      hostNetwork: true
      container:
      - name: node-daemonset
        image: prom/node-exporter:latest
        ports:
        - containerPort: 9100
          hostPort: 91100
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
        - name: sys
          mountPath: /host/sys
          readOnly: true
    volumes:
    - name: proc
      hostPath:
        path: /proc
    - name: sys
      hostPath:
        path: /sys


